force-app/main/default/objects/Router__c/Router__c.object-meta.xml
<CustomObject>
    <label>Router</label>
    <nameField>
        <label>Router Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Router__c/fields/Target_Object__c.field-meta.xml
<CustomField>
    <fullName>Target_Object__c</fullName>
    <label>Target Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Router_Rule__c/Router_Rule__c.object-meta.xml
<CustomObject>
    <label>Router Rule</label>
    <nameField>
        <label>Router Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Router Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Router_Rule__c/fields/Assigned_Count__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Count__c</fullName>
    <label>Assigned Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Router_Rule__c/fields/Assignment_Method__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Method__c</fullName>
    <label>Assignment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Duplicate Matching</fullName>
            </value>
            <value>
                <fullName>Rule-Based Assignment</fullName>
            </value>
            <value>
                <fullName>Territory Assignment</fullName>
            </value>
            <value>
                <fullName>Skill-Based Assignment</fullName>
            </value>
            <value>
                <fullName>Shark Tank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Router_Rule__c/fields/Connected_Queue__c.field-meta.xml
<CustomField>
    <fullName>Connected_Queue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connected Queue</label>
    <referenceTo>LocationWaitlist</referenceTo>
    <relationshipLabel>Router Rules</relationshipLabel>
    <relationshipName>Router_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Router_Rule__c/fields/Overflow_Behavior__c.field-meta.xml
<CustomField>
    <fullName>Overflow_Behavior__c</fullName>
    <label>Overflow Behavior</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Continue Evaluation</fullName>
            </value>
            <value>
                <fullName>Stop Evaluation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Router_Rule__c/fields/Router__c.field-meta.xml
<CustomField>
    <fullName>Router__c</fullName>
    <label>Router</label>
    <referenceTo>Router__c</referenceTo>
    <relationshipLabel>Router Rules</relationshipLabel>
    <relationshipName>Router_Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RouterController.cls
public with sharing class RouterController {
    
    @AuraEnabled(cacheable=true)
    public static List<Router_Rule__c> getRouterRules(String targetObject) {
        try {
            return [
                SELECT Id, 
                       Order__c, //Number
                       Name,
                       Enabled__c, //Boolean
                       Status__c, //Picklist
                       Assignment_Method__c, //Picklist
                       Connected_Queue__c, //Lookup to Group
                       Criteria__c, //Text
                       Overflow_Behavior__c, //Picklist
                       Assigned_Count__c//Number
                FROM Router_Rule__c
                WHERE Router__r.Name = :targetObject
                ORDER BY Order__c ASC
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error fetching router rules: ' + e.getMessage());
        }
    }


    //Added Code
    // @AuraEnabled
    // public static Router__c createRouter(String routerName,String objectName,String assignedField,String evaluationOrder) 
    // {
    //     try {
    //         Router__c newRouter = new Router__c(
    //             Name = routerName,
    //             Target_Object__c = objectName
    //             Assigned_Field__c = assignedField,
    //             Evaluation_Order__c = evaluationOrder
    //         );
    //         insert newRouter;
    //         return newRouter;
    //     } catch (Exception e) {
    //         throw new AuraHandledException('Error creating router: ' + e.getMessage()); 
    // }
    // }
}